In [2]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df=pd.read_csv("Churn_Modelling.csv")

In [5]:
df

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [30]:
df.shape

(10000, 12)

In [6]:
df.isna().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [7]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [10]:
df.duplicated().sum()

0

In [11]:
# checking class balance 
df['Exited'].value_counts()

Exited
0    7963
1    2037
Name: count, dtype: int64

In [12]:
df['Geography'].value_counts()

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

In [13]:
df['Gender'].value_counts()

Gender
Male      5457
Female    4543
Name: count, dtype: int64

In [14]:
df.drop(columns=['RowNumber','CustomerId','Surname'],inplace=True)

In [15]:
df.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0

In [22]:
# one hot encoding 

df=pd.get_dummies(df, columns=['Geography','Gender'], drop_first=True)

In [27]:
X=df.drop(columns=['Exited'])
y=df['Exited']

In [31]:
X.shape

(10000, 11)

In [32]:
y.shape

(10000,)

In [34]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [36]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.fit_transform(X_test)

In [38]:
X_train_scaled[0]

array([-0.05857382, -0.75785586, -1.38361627,  0.83783658, -0.91195944,
        0.64550866,  0.96414245, -1.68029336,  1.72572313, -0.57138416,
       -1.10303242])

In [39]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

2024-03-17 19:10:37.006761: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [65]:
model=Sequential()
model.add(Dense(11,activation='relu',input_dim=11))
model.add(Dense(11,activation='relu'))
model.add(Dense(1,activation='sigmoid'))

In [67]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_2 (Dense)             (None, 11)                132       
                                                                 
 dense_3 (Dense)             (None, 11)                132       
                                                                 
 dense_4 (Dense)             (None, 1)                 12        
                                                                 
Total params: 276 (1.08 KB)
Trainable params: 276 (1.08 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [75]:
model.compile(loss='binary_crossentropy',optimizer='Adam',metrics=['accuracy'])

In [77]:
model.fit(X_train_scaled,y_train,epochs=100,validation_split=0.2)

Epoch 1/100
200/200 [==============================] - 0s 2ms/step - loss: 0.3263 - accuracy: 0.8667 - val_loss: 0.3299 - val_accuracy: 0.8644
Epoch 2/100
200/200 [==============================] - 0s 2ms/step - loss: 0.3256 - accuracy: 0.8669 - val_loss: 0.3308 - val_accuracy: 0.8644
Epoch 3/100
200/200 [==============================] - 0s 2ms/step - loss: 0.3263 - accuracy: 0.8678 - val_loss: 0.3299 - val_accuracy: 0.8644
Epoch 4/100
200/200 [==============================] - 0s 2ms/step - loss: 0.3257 - accuracy: 0.8669 - val_loss: 0.3328 - val_accuracy: 0.8631
Epoch 5/100
200/200 [==============================] - 0s 2ms/step - loss: 0.3256 - accuracy: 0.8672 - val_loss: 0.3288 - val_accuracy: 0.8625
Epoch 6/100
200/200 [==============================] - 0s 2ms/step - loss: 0.3256 - accuracy: 0.8681 - val_loss: 0.3290 - val_accuracy: 0.8656
Epoch 7/100
200/200 [==============================] - 0s 2ms/step - loss: 0.3252 - accuracy: 0.8686 - val_loss: 0.3301 - val_accuracy: 0.8631

Epoch 58/100
200/200 [==============================] - 0s 2ms/step - loss: 0.3199 - accuracy: 0.8722 - val_loss: 0.3316 - val_accuracy: 0.8644
Epoch 59/100
200/200 [==============================] - 0s 2ms/step - loss: 0.3194 - accuracy: 0.8698 - val_loss: 0.3319 - val_accuracy: 0.8650
Epoch 60/100
200/200 [==============================] - 0s 2ms/step - loss: 0.3192 - accuracy: 0.8700 - val_loss: 0.3312 - val_accuracy: 0.8631
Epoch 61/100
200/200 [==============================] - 0s 2ms/step - loss: 0.3192 - accuracy: 0.8708 - val_loss: 0.3316 - val_accuracy: 0.8637
Epoch 62/100
200/200 [==============================] - 0s 2ms/step - loss: 0.3190 - accuracy: 0.8708 - val_loss: 0.3322 - val_accuracy: 0.8644
Epoch 63/100
200/200 [==============================] - 0s 2ms/step - loss: 0.3184 - accuracy: 0.8719 - val_loss: 0.3328 - val_accuracy: 0.8619
Epoch 64/100
200/200 [==============================] - 0s 2ms/step - loss: 0.3185 - accuracy: 0.8716 - val_loss: 0.3316 - val_accuracy:

In [71]:
model.layers[0].get_weights()

[array([[-0.22892693,  0.07046495,  0.00895045, -0.00797466, -0.34753507,
          0.14359678, -0.22596358, -0.33487645, -0.12968545,  0.03220224,
          0.11738677],
        [-0.41422564, -0.10956074, -0.17938536, -0.30670533,  0.13714516,
         -0.6522699 ,  0.39158133,  0.64737064,  0.6850022 ,  1.016476  ,
          0.6003633 ],
        [ 0.17200585, -0.34241343, -0.04593728,  0.06071462,  0.25385275,
         -0.08943048, -0.15867084, -0.26058337,  0.02681215,  0.16076846,
          0.15969422],
        [-0.4238748 ,  0.41155386, -0.32909372, -0.2298148 , -0.15660854,
         -0.06559627,  0.19606245, -0.0479312 ,  0.26973006, -0.21545258,
         -0.00139254],
        [-0.14262688, -0.01203978,  0.5022959 , -0.31701982,  0.09137948,
          0.03016748, -0.10487432, -0.9915041 ,  1.004353  , -0.8698173 ,
          0.20373769],
        [-0.69582367, -0.0105928 , -0.42285526, -0.21772201,  0.7452134 ,
          0.30170622, -0.14945912,  0.14262825, -0.04130667,  0.0017706

In [72]:
y_log=model.predict(X_test_scaled)

63/63 [==============================] - 0s 1ms/step


In [73]:
y_predicted=np.where(y_log>0.5 , 1 , 0)


In [74]:
y_predicted

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]])

In [61]:
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report

In [59]:
accuracy_score(y_test,y_predicted)

0.815

In [60]:
confusion_matrix(y_test,y_predicted)

array([[1504,   69],
       [ 301,  126]])

In [63]:
print(classification_report(y_test,y_predicted))

              precision    recall  f1-score   support

           0       0.83      0.96      0.89      1573
           1       0.65      0.30      0.41       427

    accuracy                           0.81      2000
   macro avg       0.74      0.63      0.65      2000
weighted avg       0.79      0.81      0.79      2000

